version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/SubtitleSeeker  # Adjust the volume path based on your project structure
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    links:
      - redis

  celery:
    build: .
    command: celery -A subtitlesApp.celery worker --pool=solo -l info
    depends_on:
      - web
      - redis
    links:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
