# Generated by Django 4.2.7 on 2023-11-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subtitlesApp", "0002_alter_subtitle_subtitle_file_alter_subtitle_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtitle",
            name="subtitle_file",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="video",
            field=models.FileField(upload_to=""),
        ),
    ]
